name: BuildAndPushImageOnHarborAndUpdateArgoCDConfig

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Show environment
        run: echo "${{ secrets.REPOSITORY_PASSWORD }}"
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: http://registry.sotaicg.com/
          username: ${{ secrets.REPOSITORY_USERNAME }}
          password: ${{ secrets.REPOSITORY_PASSWORD }}
      - name: Build and push image to Harbor
        run: |
          docker build ./ -t registry.sotaicg.com/library/chaturmail-backend:${{ github.run_number }}
          docker push registry.sotaicg.com/library/chaturmail-backend:${{ github.run_number }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull registry.sotaicg.com/library/chaturmail-backend:${{ github.run_number }}

      - name: Run application
        run: |
          docker run -d -p 80:3000 -n name reactjs-container registry.sotaicg.com/library/chaturmail-backend:${{ github.run_number }}

