name: CI/CD for development environment

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  REPOSIORY_NAME: registry.sotaicg.com
  PROJECT_NAME: library
  TAG: latest

jobs:

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/develop')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: http://registry.sotaicg.com/
          username: ${{ secrets.REPOSITORY_USERNAME }}
          password: ${{ secrets.REPOSITORY_PASSWORD }}
          
      - name: Build image to Harbor repository
        run: docker build ./ -t $REPOSIORY_NAME/$PROJECT_NAME/platform-backend:$TAG

      - name: Push image to Harbor repository
        run: docker push $REPOSIORY_NAME/$PROJECT_NAME/platform-backend:$TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: pwd
