name: CI/CD for development environment

on:
  push:
    branches:
      - develop
    tags:
      - '*'  # Tất cả các tag
  pull_request:
    branches:
      - develop

env:
  REPOSITORY_NAME: registry.sotaicg.com
  PROJECT_NAME: dev-backend
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: http://registry.sotaicg.com/
          username: ${{ secrets.REPOSITORY_USERNAME }}
          password: ${{ secrets.REPOSITORY_PASSWORD }}
          
      - name: Determine tag
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            export TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          else
            export TAG="${{ env.TAG }}"
          fi
          echo "Tag: $TAG"

      - name: Build image to Harbor repository
        run: docker build ./ -t ${{ env.REPOSITORY_NAME }}/${{ env.PROJECT_NAME }}/platform-backend:${TAG}

      - name: Push image to Harbor repository
        run: docker push ${{ env.REPOSITORY_NAME }}/${{ env.PROJECT_NAME }}/platform-backend:${TAG}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            ls
            cd ./dev-environment/docker-dev-datalake-platform
            docker compose -f docker-compose-dev.yaml up --build -d
            docker exec -it nginx nginx -s reload || { echo "Error: Failed to restart nginx"; exit 1; }
