name: BuildAndPushImageOnHarborAndUpdateArgoCDConfig

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Show environment
      run: echo "${{ secrets.REPOSITORY_PASSWORD  }}"
    - uses: docker/login-action@v1
      with:
        registry: http://registry.sotaicg.com/
        username: ${{ secrets.REPOSITORY_PASSWORD  }}
        password: ${{ secrets.REPOSITORY_USERNAME }}
